Repository SWYP-Playground/Playground-Front, pull requests merged in 2024-12, with the labels that each got.

#14 회원가입 페이지 및 가입 완료 팝업 구현
  package.json
  src/pages/SignUpPage/SignUpCompletePopup.tsx
  src/pages/SignUpPage/SignUpPage.style.ts
  src/pages/SignUpPage/SignUpPage.tsx
Labels: ✨ Feature

#16 카카오 지도 관련 컴포넌트 설정
  src/assets/svg/create-room.svg
  src/assets/svg/crosshair.svg
  src/assets/svg/player-marker.svg
  src/assets/svg/reset-search.svg
  src/assets/svg/search.svg
  src/components/common/BottomSheet/CustomBottomSheet.tsx
  src/components/playGround/PlayGroundButton/PlayGroundButton.style.ts
  src/components/playGround/PlayGroundButton/PlayGroundButton.tsx
  src/components/playGround/PlayGroundMap/PlayGroundMap.style.ts
  src/components/playGround/PlayGroundMap/PlayGroundMap.tsx
  src/components/playGround/PlayGroundSearchBar/PlayGroundSearchBar.style.ts
  src/components/playGround/PlayGroundSearchBar/PlayGroundSearchBar.tsx
  src/constants/map.ts
  src/constants/path.ts
  src/hooks/common/useDebounce.ts
  src/hooks/common/useKakaoLoader.ts
  src/hooks/common/useLocation.ts
  src/pages/CreatePlaygroundPage/CreatePlaygroundPage.tsx
  src/pages/FindPlaygroundFriendPage/FindPlaygroundFriendPage.tsx
  src/pages/PlaygroundSearchPage/PlaygroundSearchPage.style.tsx
  src/pages/PlaygroundSearchPage/PlaygroundSearchPage.tsx
  src/router/AppRouter.tsx
  src/router/lazy.ts
Labels: ✨ Feature

#22 바텀 네비게이션 바 컴포넌트 구현
  src/App.tsx
  src/components/layout/BottomNav/BottomNav.style.ts
  src/components/layout/BottomNav/BottomNav.tsx
  src/components/layout/Header/Header.style.ts
  src/components/layout/Header/Header.tsx
  src/components/playGround/PlayGroundButton/PlayGroundButton.style.ts
  src/pages/FindPlaygroundFriendPage/FindPlaygroundFriendPage.style.ts
  src/pages/FindPlaygroundFriendPage/FindPlaygroundFriendPage.tsx
  src/pages/SignInPage/SignInPage.style.ts
  src/pages/SignInPage/SignInPage.tsx
  src/pages/SignUpPage/SignUpPage.style.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/styles/GlobalStyle.ts
Labels: ✨ Feature

#23 친구 온도 관련 페이지 구현
  src/assets/svg/report.svg
  src/assets/svg/temperature.svg
  src/components/temperature/TemperatureButton/TemperatureButton.style.ts
  src/components/temperature/TemperatureButton/TemperatureButton.tsx
  src/components/temperature/TemperatureModal/TemperatureModal.style.ts
  src/components/temperature/TemperatureModal/TemperatureModal.tsx
  src/constants/text.ts
  src/pages/FriendsPlayedPage/FriendsPlayedPage style.ts
  src/pages/FriendsPlayedPage/FriendsPlayedPage.tsx
  src/pages/ReportFriendPage/ReportFriendPage.style.ts
  src/pages/ReportFriendPage/ReportFriendPage.tsx
Labels: ✨ Feature

#24 프로필 작성 페이지 구현
  src/assets/svg/pencil.svg
  src/assets/svg/plus.svg
  src/components/popUp/SignUpCompletePopup.tsx
  src/components/profile/Button/RadioButton.tsx
  src/components/profile/Button/ToggleButton.tsx
  src/components/profile/EditProfile/AdditionalInfoSection.tsx
  src/components/profile/EditProfile/FamilyInfoSection.tsx
  src/components/profile/EditProfile/ProfileImageSection.tsx
  src/hooks/signUp/useSignUpForm.ts
  src/pages/EditProfilePage/EditProfilePage.style.ts
  src/pages/EditProfilePage/EditProfilePage.tsx
  src/pages/FindAccountPage/FindAccountPage.style.ts
  src/pages/FindAccountPage/FindAccountPage.tsx
  src/pages/SignInPage/SignInPage.style.ts
  src/pages/SignInPage/SignInPage.tsx
  src/pages/SignUpPage/SignUpPage.style.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/styles/GlobalStyle.ts
Labels: ✨ Feature

#27 마이페이지 UI 퍼블리싱
  src/assets/svg/setting.svg
  src/components/profile/MyPage/ChildCard.tsx
  src/components/profile/MyPage/ContactUsSection.tsx
  src/components/profile/MyPage/MyGroupsSection.tsx
  src/components/profile/MyPage/ProfileDetailSection.tsx
  src/components/profile/MyPage/ProgressBar.tsx
  src/components/profile/MyPage/RecentFriendsSection.tsx
  src/constants/path.ts
  src/main.tsx
  src/pages/FriendRecommendedPage/FriendRecommendedPage.style.ts
  src/pages/FriendRecommendedPage/FriendRecommendedPage.tsx
  src/pages/MyRecruitmentsPage/MyRecruitmentsPage.style.ts
  src/pages/MyRecruitmentsPage/MyRecruitmentsPage.tsx
  src/pages/ProfilePage/ProfilePage.style.ts
  src/pages/ProfilePage/ProfilePage.tsx
  src/router/AppRouter.tsx
  src/router/lazy.ts
  src/types/emotion.d.ts
Labels: ✨ Feature

#30 마이페이지 관련된 추가 페이지 및 컴포넌트 퍼블리싱
  src/components/popUp/DeletePopup.tsx
  src/components/profile/Button/SettingButton.tsx
  src/components/profile/EditProfile/ExtraImageSection.tsx
  src/components/profile/MyPage/ProfileDetailSection.tsx
  src/constants/path.ts
  src/hooks/mypage/useCardData.ts
  src/hooks/mypage/useUserSettingForm.ts
  src/pages/EditProfilePage/EditProfilePage.style.ts
  src/pages/EditProfilePage/EditProfilePage.tsx
  src/pages/FriendsPlayedPage/FriendsPlayedPage style.ts
  src/pages/FriendsPlayedPage/FriendsPlayedPage.tsx
  src/pages/MyRecruitmentsPage/MyRecruitmentsPage.style.ts
  src/pages/MyRecruitmentsPage/MyRecruitmentsPage.tsx
  src/pages/ProfileInfoPage/ProfileInfoPage.syle.ts
  src/pages/ProfileInfoPage/ProfileInfoPage.tsx
  src/pages/ProfilePage/ProfilePage.style.ts
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/UserSettingPage/UserSettingPage.style.ts
  src/pages/UserSettingPage/UserSettingPage.tsx
  src/router/AppRouter.tsx
  src/router/lazy.ts
Labels: ✨ Feature

#31 대소문자 구분으로 발생한 파일 경로 에러 해결
  src/pages/SignUpPage/SignUpPage.tsx
Labels: 🐞 Bug

#35 메인페이지 UI 구현
  src/assets/png/banner.png
  src/assets/svg/logo-horizon.svg
  src/components/common/RequirementRoom/RequirementRoom.style.ts
  src/components/common/RequirementRoom/RequirementRoom.tsx
  src/components/profile/MyPage/MyGroupsSection.tsx
  src/pages/MainPage/MainPage.style.ts
  src/pages/MainPage/MainPage.tsx
Labels: ✨ Feature

#38 바텀 네비게이션 활성화 설정 & 글꼴 적용
  package.json
  src/assets/svg/create-fill.svg
  src/assets/svg/create.svg
  src/assets/svg/home-fill.svg
  src/assets/svg/home.svg
  src/assets/svg/message-fill.svg
  src/assets/svg/message.svg
  src/assets/svg/profile-fill.svg
  src/assets/svg/profile.svg
  src/assets/svg/search-fill.svg
  src/assets/svg/search.svg
  src/components/layout/BottomNav/BottomNav.tsx
  src/main.tsx
  src/styles/GlobalStyle.ts
  vercel.json
  yarn.lock
Labels: 🔨 Refactor

#44 회원가입 API 연결
  src/api/axiosInstance.ts
  src/api/user/postSignUp.ts
  src/components/profile/Button/ToggleButton.tsx
  src/components/profile/EditProfile/AdditionalInfoSection.tsx
  src/components/profile/EditProfile/FamilyInfoSection.tsx
  src/components/profile/EditProfile/ProfileImageSection.tsx
  src/hooks/api/useLogInMutation.ts
  src/hooks/api/useSignUpMutation.ts
  src/hooks/signUp/useSignUpForm.ts
  src/pages/CreateProfilePage/CreateProfilePage.tsx
  src/pages/EditProfilePage/EditProfilePage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/store/authStore.ts
  src/store/signUpStore.ts
Labels: ✨ Feature

#46 interceptor 토큰 에러 관련 버그 해결 / 카카오 지도 관련 버그 해결
  src/api/axiosInstance.ts
  src/api/interceptors.ts
  src/components/playGround/PlayGroundMap/PlayGroundMap.tsx
  src/hooks/api/useCommentMutation.ts
  src/hooks/api/useDeleteCommentMutation.ts
  src/hooks/api/useDeleteNoteMutation.ts
  src/hooks/api/useDeleteParentMutation.ts
  src/hooks/api/useLogOutMutation.ts
  src/hooks/api/useNoteMutation.ts
  src/hooks/api/useParticipateFindFriendMutation.ts
  src/hooks/api/useRegisterFindFriendMutation.ts
  src/hooks/api/useReportMutation.ts
  src/hooks/api/useUpdateCommentMutation.ts
  src/hooks/api/useUpdateFindFriendInfoMutation.ts
  src/hooks/api/useUpdateNoteMutation.ts
  src/hooks/api/useUpdateParentMutation.ts
  src/pages/CreateProfilePage/CreateProfilePage.tsx
Labels: 🐞 Bug

#48 프로필 조회 API 연결
  src/api/parent/getParentById.ts
  src/api/user/postLogin.ts
  src/api/user/postSignUp.ts
  src/assets/png/profile1.png
  src/components/profile/MyPage/ProfileDetailSection.tsx
  src/hooks/api/useLogInMutation.ts
  src/pages/ProfileInfoPage/ProfileInfoPage.tsx
  src/pages/ProfilePage/ProfilePage.style.ts
  src/pages/ProfilePage/ProfilePage.tsx
  src/store/authStore.ts
  src/types/parent.ts
Labels: ✨ Feature

#50 프로필 수정 페이지 / 메인 페이지 / 계정 찾기 및 탈퇴 API 연결
  src/api/findFriend/getMainFindFriendList.ts
  src/api/parent/patchParent.ts
  src/components/profile/EditProfile/FamilyInfoSection.tsx
  src/components/profile/MyPage/ContactUsSection.tsx
  src/hooks/api/useMainFindFriendListQuery.ts
  src/pages/EditProfilePage/EditProfilePage.tsx
  src/pages/FindAccountPage/FindAccountPage.style.ts
  src/pages/FindAccountPage/FindAccountPage.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/UserSettingPage/UserSettingPage.tsx
Labels: ✨ Feature

#51 모집글 수정 & 친구 쪽지 작성 구현 / 마이 프로필 페이지 & 유저 정보 조회 페이지 수정
  src/api/findFriend/deleteFindFriend.ts
  src/components/layout/BottomNav/BottomNav.tsx
  src/components/playGround/FinishTimePicker/FinishTimePicker.tsx
  src/components/playGround/MeetTimePicker/MeetTimePicker.tsx
  src/components/playGround/PlayGroundForm/PlayGroundForm.tsx
  src/components/playGround/PlayGroundFormSearchBar/PlayGroundFormSearchBar.style.ts
  src/components/playGround/PlayGroundFormSearchBar/PlayGroundFormSearchBar.tsx
  src/components/profile/MyPage/ChildCard.tsx
  src/components/profile/MyPage/ProfileDetailSection.tsx
  src/constants/path.ts
  src/hooks/api/useDeleteRoomMutation.ts
  src/hooks/api/useFindFriendInfoQuery.ts
  src/hooks/api/useNoteMutation.ts
  src/hooks/api/useUpdateFindFriendInfoMutation.ts
  src/pages/CreatePlaygroundPage/CreatePlaygroundPage.tsx
  src/pages/EditProfilePage/EditProfilePage.tsx
  src/pages/FriendsPlayedPage/FriendsPlayedPage.tsx
  src/pages/MyProfilePage/MyProfilePage.style.ts
  src/pages/MyProfilePage/MyProfilePage.tsx
  src/pages/MyRecruitmentsPage/MyRecruitmentsPage.tsx
  src/pages/PlaygroundMessagePage/PlaygroundMessagePage.tsx
  src/pages/PlaygroundRoomListPage/PlaygroundRoomListPage.style.ts
  src/pages/PlaygroundRoomPage/PlaygroundRoomPage.style.ts
  src/pages/PlaygroundRoomPage/PlaygroundRoomPage.tsx
  src/pages/ProfileInfoPage/ProfileInfoPage.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ReportFriendPage/ReportFriendPage.tsx
  src/router/AppRouter.tsx
  src/router/lazy.ts
  src/utils/getDecodedTokenData.ts
  src/utils/parseScheduleTime.ts
Labels: ✨ Feature, 🔨 Refactor

#55 !HOTFIX : useEffect 호출 오류 수정
  src/pages/MyProfilePage/MyProfilePage.tsx
  src/pages/PlaygroundMessagePage/PlaygroundMessagePage.tsx
  src/pages/ProfileInfoPage/ProfileInfoPage.tsx
  src/pages/ReportFriendPage/ReportFriendPage.tsx
Labels: 🐞 Bug

#57 카카오 주소 검색 API 연결
  index.html
  package.json
  src/components/profile/EditProfile/AddressSearchModal.tsx
  src/components/profile/EditProfile/ProfileImageSection.tsx
  src/pages/EditProfilePage/EditProfilePage.style.ts
  yarn.lock
Labels: ✨ Feature

#59 도로명주소 수정 / 에러 페이지 리팩토링
  src/App.tsx
  src/components/common/Error/Error.style.ts
  src/components/common/Error/Error.tsx
  src/components/popUp/SignUpCompletePopup.tsx
  src/components/profile/EditProfile/ProfileImageSection.tsx
  src/constants/path.ts
  src/pages/SignUpCompletePage/SignUpCompletePage.tsx
  src/router/AppRouter.tsx
  src/router/lazy.ts
Labels: 🔨 Refactor

#60 프로필 작성 페이지 에러 해결 및 로그아웃 API 연결
  src/components/popUp/SignUpCompletePopup.tsx
  src/components/profile/Button/ToggleButton.tsx
  src/components/profile/EditProfile/FamilyInfoSection.tsx
  src/components/profile/MyPage/ContactUsSection.tsx
  src/hooks/api/useLogOutMutation.ts
Labels: 🐞 Bug, ✨ Feature, 🔨 Refactor

#62 Refactor/#61 rerendering recent
  src/components/temperature/TemperatureModal/TemperatureModal.tsx
  src/constants/path.ts
  src/hooks/api/useMainFindFriendListQuery.ts
  src/pages/ActiveRecruitmentsPage/ActiveRecruitmentsPage.tsx
  src/pages/FriendsPlayedPage/FriendsPlayedPage.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MyProfilePage/MyProfilePage.tsx
  src/pages/MyRecruitmentsPage/MyRecruitmentsPage.tsx
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/ReportFriendPage/ReportFriendPage.tsx
  src/router/AppRouter.tsx
  src/types/report.ts
Labels: 🔨 Refactor

#63 놀이터 검색 관련 수정
  src/components/playGround/PlayGroundFormSearchBar/PlayGroundFormSearchBar.tsx
  src/components/playGround/PlayGroundSearchBar/PlayGroundSearchBar.tsx
  src/hooks/api/usePlaygroundsQuery.ts
  src/pages/FindPlaygroundFriendPage/FindPlaygroundFriendPage.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/PlaygroundSearchPage/PlaygroundSearchPage.tsx
Labels: 🐞 Bug, 🔨 Refactor

#64 프로필 이미지 랜덤 렌더링 기능 구현
  src/assets/png/profile2.png
  src/assets/png/profile3.png
  src/assets/png/profile4.png
  src/assets/png/profile5.png
  src/components/common/Card/Card.tsx
  src/components/playGround/PlayGroundParticipant/PlayGroundParticipant.tsx
  src/components/profile/EditProfile/ProfileImageSection.tsx
  src/components/profile/MyPage/ProfileDetailSection.tsx
  src/components/profile/RandomImage.tsx
Labels: ✨ Feature
